name: Build and Deploy Spring Boot with Docker

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로우 실행
  pull_request:
    branches:
      - main  # main 브랜치로 풀 리퀘스트가 생성될 때도 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2  # 리포지토리 코드 체크아웃

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # JDK 11 설정

    - name: Build with Maven
      run: mvn clean install  # Maven으로 Spring Boot 애플리케이션 빌드

    - name: Build Docker image
      run: |
        docker build -t myusername/my-app:${{ github.sha }} .  # Docker 이미지 빌드
        docker tag myusername/my-app:${{ github.sha }} myusername/my-app:latest  # 최신 태그 추가

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에서 Docker Hub 사용자명 가져오기
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에서 Docker Hub 비밀번호 가져오기

    - name: Push Docker image
      run: |
        docker push myusername/my-app:${{ github.sha }}  # Docker Hub에 이미지 푸시
        docker push myusername/my-app:latest  # 최신 태그 푸시
